### PR TITLE
MODLOGIN-75

### PR DESCRIPTION
**Pull request by OleksiiMaksymov**
Add and Implement new "EventsLogApi" component
 * Add implementation `/authn/log/events` which is accessible through OKAPI
 * Add rest tests

### CODE REVIEW

**Comment by OleksiiMaksymov** [comment]
Thanks for the comment.

**Comment by kurtnordstrom** [comment]
Haven't reviewed the code yet, but I have noticed that you've modified the NEWS file. We have decided to stop doing this between releases, and instead update the NEWS when the releases are made, based on the release number flagged in Jira.

See clarification: https://dev.folio.org/guidelines/release-procedures/#prepare-the-news-document

**Comment by kurtnordstrom** [comment]
Is there any reason that "{userId}" is used as the id specifier in the module descriptor for the events endpoints?

**Comment by adamdickmeiss** [comment]
About the news.. Please put the documentation either in the git log message.. or in a Jira issue. Then the news can be compiled nicely.. We do encourage people to document .. just not in the news along the way, because it ALWAYS leads to conflicts with many coders on same code base (while Git OTOH can do nicely with concurrent things:-)

**Comment by OleksiiMaksymov** [comment]
About the `logEvent.json` schema. This module will subscribe to events in the `mod-audit ` module that are described in https://github.com/folio-org/mod-audit/blob/master/ramls/audit.json. In this json, fields "auth_error" and "module_error" are also of type object.

**Pull request merged**
